### ISSUE TITLE
Complete or rearrange codes

### ISSUE THREAD

**Issue by abhavgoel** [abhavgoel/TribeVibe#1]

**Comment by PriyanshiNagpal** [comment]
I write codes in C++, can I contribute?

**Comment by abhavgoel** [comment]
> I write codes in C++, can I contribute?

yeah just make a folder of c++ and add codes to it

**Comment by PriyanshiNagpal** [comment]
Can I make changes to .c files in .cpp?

**Comment by abhavgoel** [comment]
> Can I make changes to .c files in .cpp?

no no just leave .c files for now i need something to do with them later, u can aadd cpp files if u want in a different folder

**Comment by PriyanshiNagpal** [comment]
okay!!
I am adding a new cpp folder

**Comment by abhavgoel** [comment]
> okay!!
> I am adding a new cpp folder

ive added the folder, now u can contribute to it

**Comment by AbhirupB** [comment]
can I add Python codes??

**Comment by abhavgoel** [comment]
> can I add Python codes??

yeah but make sure to make a python folder first

**Comment by AbhirupB** [comment]
please add python as a tag

**Comment by shreya3071** [comment]
Hey Abhavgoel, I want to contribute codes in  C++ please assign it to me.

**Comment by ryguigas0** [comment]
Hey I write codes in elixir, can I contribute?

**Comment by abhavgoel** [comment]
> Hey I write codes in elixir, can I contribute?

yupp sure.. just add an elixir folder prior

**Comment by yamini3707** [comment]
Hey, I want to add C++ code. Please assign me this.

**Comment by prehans** [comment]
Hello I want to add codes in cpp can you assign this to me?? @abhavgoel
